//// <auto-generated />
//using System;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
//using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
//using Shop.Domain;

//#nullable disable

//namespace Shop.Domain.Migrations
//{
//    [DbContext(typeof(DBContext))]
//    [Migration("20260424085352_InitialCreate")]
//    partial class InitialCreate
//    {
//        /// <inheritdoc />
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "8.0.26")
//                .HasAnnotation("Relational:MaxIdentifierLength", 63);

//            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

//            modelBuilder.Entity("Shop.Domain.Entities.TaskApp", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("integer");

//                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

//                    b.Property<DateTime>("ExpiredDate")
//                        .HasColumnType("timestamp with time zone");

//                    b.Property<bool>("IsCompleted")
//                        .HasColumnType("boolean");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<int>("UserID")
//                        .HasColumnType("integer");

//                    b.HasKey("Id");

//                    b.HasIndex("UserID");

//                    b.ToTable("Tasks");
//                });

//            modelBuilder.Entity("Shop.Domain.Entities.User", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("integer");

//                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

//                    b.Property<string>("Login")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("Password")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("email")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.Property<string>("firstName")
//                        .IsRequired()
//                        .HasColumnType("text");

//                    b.HasKey("Id");

//                    b.ToTable("Users");
//                });

//            modelBuilder.Entity("Shop.Domain.Entities.TaskApp", b =>
//                {
//                    b.HasOne("Shop.Domain.Entities.User", "User")
//                        .WithMany()
//                        .HasForeignKey("UserID")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("User");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
